
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Foods').del()
    .then(function () {
      // Inserts seed entries
      return knex('Foods').insert([
        {id: 1, name: 'Apples', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 3},
        {id: 2, name: 'Bananas', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 4},
        {id: 3, name: 'Kiwifruit', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 4},
        {id: 4, name: 'Cardboard', category: 'Grain', measurement_units: 'Grams', sweet: true, savoury: true, sloppiness: 1},
        {id: 5, name: 'Newspaper', category: 'Grain', measurement_units: 'Grams', sweet: true, savoury: true, sloppiness: 1},
        {id: 6, name: 'Oats', category: 'Grain', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 1},
        {id: 7, name: 'Cocoa', category: 'Condiment', measurement_units: 'Tablespoons', sweet: true, savoury: false, sloppiness: 1},
        {id: 8, name: 'Curry powder', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 1},
        {id: 9, name: 'Frozen vegetables', category: 'Vegetable', measurement_units: 'Cups', sweet: false, savoury: true, sloppiness: 2},
        {id: 10, name: 'Cinnamon', category: 'Condiment', measurement_units: 'Teaspoons', sweet: true, savoury: false, sloppiness: 1},
        {id: 11, name: 'Mustard', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 4},
        {id: 12, name: 'Dates', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 1},
        {id: 13, name: 'Frozen berries', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 3},
        {id: 14, name: 'Broccoli', category: 'Vegetable', measurement_units: 'Cups', sweet: false, savoury: true, sloppiness: 2},
        {id: 15, name: 'Lentils', category: 'Legume', measurement_units: 'Cups', sweet: false, savoury: true, sloppiness: 1},
        {id: 16, name: 'Chickpeas', category: 'Legume', measurement_units: 'Cups', sweet: false, savoury: true, sloppiness: 2},
        {id: 17, name: 'Peanut butter', category: 'Condiment', measurement_units: 'Tablespoons', sweet: true, savoury: true, sloppiness: 3},
        {id: 18, name: 'Tahini', category: 'Condiment', measurement_units: 'Tablespoons', sweet: true, savoury: true, sloppiness: 3},
        {id: 19, name: 'Almond butter', category: 'Condiment', measurement_units: 'Tablespoons', sweet: true, savoury: false, sloppiness: 3},
        {id: 20, name: 'Miso', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 2},
        {id: 21, name: 'Olives', category: 'Condiment', measurement_units: 'Grams', sweet: false, savoury: true, sloppiness: 2},
        {id: 22, name: 'Ginger', category: 'Condiment', measurement_units: 'Grams', sweet: true, savoury: true, sloppiness: 1},
        {id: 23, name: 'Liquid smoke', category: 'Condiment', measurement_units: 'Teaspoons', sweet: false, savoury: true, sloppiness: 5},
        {id: 24, name: 'Hot sauce', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 5},
        {id: 25, name: 'Chilli powder', category: 'Condiment', measurement_units: 'Teaspoons', sweet: false, savoury: true, sloppiness: 1},
        {id: 26, name: 'Persimmons', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 3},
        {id: 27, name: 'Figs', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 1},
        {id: 28, name: 'Tofu', category: 'Legume', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 3},
        {id: 29, name: 'Weetbix', category: 'Grain', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 1},
        {id: 30, name: 'Baked beans', category: 'Legume', measurement_units: 'Cups', sweet: false, savoury: true, sloppiness: 4},
        {id: 31, name: 'Beetroot', category: 'Vegetable', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 2},
        {id: 32, name: 'Pumpkin', category: 'Vegetable', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 3},
        {id: 33, name: 'Dried fungus', category: 'Vegetable', measurement_units: 'Cups', sweet: false, savoury: true, sloppiness: 1},
        {id: 34, name: 'Seaweed', category: 'Vegetable', measurement_units: 'Cups', sweet: false, savoury: true, sloppiness: 1},
        {id: 35, name: 'Nutritional yeast', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 1},
        {id: 36, name: 'Onions', category: 'Vegetable', measurement_units: 'Cups', sweet: false, savoury: true, sloppiness: 2},
        {id: 37, name: 'Kimchi', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 4},
        {id: 38, name: 'Mandarins', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 4},
        {id: 39, name: 'Grapes', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 3},
        {id: 40, name: 'Pears', category: 'Fruit', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 3},
        {id: 41, name: 'Almond milk', category: 'Liquid', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 5},
        {id: 42, name: 'Soymilk', category: 'Liquid', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 5},
        {id: 43, name: 'Tinned tomatoes', category: 'Vegetable', measurement_units: 'Cups', sweet: false, savoury: true, sloppiness: 5},
        {id: 44, name: 'Orange juice', category: 'Liquid', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 5},
        {id: 45, name: 'Apple juice', category: 'Liquid', measurement_units: 'Cups', sweet: true, savoury: false, sloppiness: 5},
        {id: 46, name: 'Kale', category: 'Vegetable', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 2},
        {id: 47, name: 'Black rice', category: 'Grain', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 1},
        {id: 48, name: 'Red rice', category: 'Grain', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 1},
        {id: 49, name: 'Green curry paste', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 3},
        {id: 50, name: 'Coriander', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 2},
        {id: 51, name: 'Basil', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 2},
        {id: 52, name: 'Carrot', category: 'Vegetable', measurement_units: 'Cups', sweet: true, savoury: true, sloppiness: 3},
        {id: 53, name: 'Salsa', category: 'Condiment', measurement_units: 'Tablespoons', sweet: false, savoury: true, sloppiness: 4},
        {id: 54, name: 'Carob powder', category: 'Condiment', measurement_units: 'Tablespoons', sweet: true, savoury: false, sloppiness: 1}
      ]);
    });
};
